# Generated by Django 3.0.4 on 2020-03-17 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
        ('users', '0002_user_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credo_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='credo_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.CredoUser'),
        ),
    ]
