# Generated by Django 3.0.3 on 2020-02-23 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('definitions', '0001_initial'),
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='definitions.Attribute')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Detection')),
            ],
            options={
                'default_permissions': ('view', 'add', 'change', 'delete'),
                'unique_together': {('detection', 'attribute', 'author')},
            },
        ),
    ]
