# Generated by Django 3.0.6 on 2020-05-26 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CredoUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('display_name', models.CharField(max_length=50)),
            ],
            options={
                'default_permissions': ('view', 'add', 'change', 'delete'),
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('device_type', models.CharField(default='phone_android', max_length=255)),
                ('device_model', models.CharField(max_length=255)),
                ('system_version', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.CredoUser')),
            ],
            options={
                'default_permissions': ('view', 'add', 'change', 'delete'),
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, unique=True)),
            ],
            options={
                'default_permissions': ('view', 'add', 'change', 'delete'),
            },
        ),
        migrations.CreateModel(
            name='Ping',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.BigIntegerField(db_index=True)),
                ('time_received', models.BigIntegerField(blank=True)),
                ('delta_time', models.IntegerField(blank=True, null=True)),
                ('on_time', models.IntegerField(blank=True, default=0, null=True)),
                ('metadata', models.TextField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.CredoUser')),
            ],
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.BigIntegerField(db_index=True)),
                ('time_received', models.BigIntegerField(blank=True)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('provider', models.CharField(blank=True, max_length=255)),
                ('metadata', models.TextField(blank=True, null=True)),
                ('frame_content', models.BinaryField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('has_image', models.BooleanField(db_index=True)),
                ('mime', models.CharField(blank=True, max_length=32, null=True)),
                ('detection_width', models.IntegerField(blank=True, null=True)),
                ('detection_height', models.IntegerField(blank=True, null=True)),
                ('detection_inner', models.NullBooleanField()),
                ('random', models.IntegerField(blank=True, null=True)),
                ('score', models.IntegerField(default=0)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Device')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.CredoUser')),
            ],
            options={
                'default_permissions': ('view', 'add', 'change', 'delete'),
                'index_together': {('has_image', 'score', 'random'), ('user', 'has_image', 'score', 'random'), ('team', 'has_image', 'score', 'random')},
            },
        ),
    ]
