# Generated by Django 3.0.4 on 2020-03-17 09:17

from django.db import migrations, models

from database.models import Detection


def post_migration(arg1, arg2):
    Detection.objects.filter(mime__isnull=True).update(has_image=False)


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='has_image',
            field=models.BooleanField(db_index=True, default=True),
            preserve_default=False,
        ),
        migrations.RunPython(post_migration),
        migrations.AlterField(
            model_name='detection',
            name='mime',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterIndexTogether(
            name='detection',
            index_together={('user', 'has_image', 'score', 'random'), ('team', 'has_image', 'score', 'random'), ('has_image', 'score', 'random')},
        ),
    ]
