# Generated by Django 3.0.3 on 2020-02-23 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from definitions.models import Attribute
from users.models import User


def post_migrations(arg1, arg2):
    from credo_classification.settings import INIT_ADMIN_USER
    u = User.objects.filter(username=INIT_ADMIN_USER).first()
    Attribute.objects.create(name='accuracy', description='GPS accuaracy', author=u)
    Attribute.objects.create(name='latitude', description='GPS latitude', author=u)
    Attribute.objects.create(name='longitude', description='GPS longitude', author=u)
    Attribute.objects.create(name='altitude', description='GPS altitude', author=u)
    Attribute.objects.create(name='height', description='Height of image frame', author=u)
    Attribute.objects.create(name='width', description='Width of image frame', author=u)
    Attribute.objects.create(name='x', description='X on image of center of crop', author=u)
    Attribute.objects.create(name='y', description='Y on image of center of crop', author=u)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('definitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='relation',
            name='dest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relation_dest', to='definitions.Attribute'),
        ),
        migrations.AddField(
            model_name='relation',
            name='src',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relation_src', to='definitions.Attribute'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='relation',
            unique_together={('src', 'dest')},
        ),
        migrations.RunPython(post_migrations),
    ]
