# Generated by Django 3.0.6 on 2020-05-26 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('definitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='relation',
            name='dest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relation_dest', to='definitions.Attribute'),
        ),
        migrations.AddField(
            model_name='relation',
            name='src',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relation_src', to='definitions.Attribute'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterUniqueTogether(
            name='relation',
            unique_together={('src', 'dest')},
        ),
    ]
