# Generated by Django 3.0.3 on 2020-03-03 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from credo_classification.settings import INIT_ADMIN_USER
from definitions.models import Attribute
from users.models import User


def post_migrations(arg1, arg2):
    u = User.objects.filter(username=INIT_ADMIN_USER).first()

    Attribute.objects.update(kind='b', active=True)
    Attribute.objects.create(name='spot', description='Spot-like hit', kind='c', author=u, active=True)
    Attribute.objects.create(name='worm', description='Worm-like hit', kind='c', author=u, active=True)
    Attribute.objects.create(name='track', description='Track-like hit', kind='c', author=u, active=True)
    Attribute.objects.create(name='artifact', description='Artifact (fake hit: hot pixel, damage of CMOS/CCD, deliberate fraud)', kind='c', author=u, active=True)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('definitions', '0002_auto_20200223_1435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'ordering': ['name'], 'verbose_name': 'Attribute', 'verbose_name_plural': 'Attributes'},
        ),
        migrations.AddField(
            model_name='attribute',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='kind',
            field=models.CharField(choices=[('b', 'Build-in'), ('c', 'Classification by user'), ('o', 'Others')], default='o', max_length=1, verbose_name='Kind'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.RunPython(post_migrations),
    ]
