# Generated by Django 3.0.3 on 2020-03-03 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0002_auto_20200223_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classified',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date of classified')),
                ('detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Detection', verbose_name='Detection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Classified detection',
                'verbose_name_plural': 'Classified detections',
                'default_permissions': ('view', 'add', 'change', 'delete'),
                'unique_together': {('user', 'detection')},
            },
        ),
    ]
