# Generated by Django 3.0.4 on 2020-03-15 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionscore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterUniqueTogether(
            name='detectionscore',
            unique_together={('user', 'detection', 'kind')},
        ),
    ]
